# site URL: https://makeup.com.ua/ua/


logo_xpath = '//*[starts-with(@class, "logo")]'
auth_button_xpath = '//*[@class="header-top"]//div[@data-popup-handler]'
basket_xpath = '//*[@class="header-right"]/child::div/div[@data-popup-handler]/following-sibling::div/span'
brands_header_xpath = '//*[starts-with(@class, "page-header") and text()="Пропозиції брендів"]'
brands_first_carousel_element_xpath = '//*[@class="simple-slider-list-wrap"]//li[@data-position="1"]'
feedbacks_link_xpath = '//*[@class="simple-slider-list-wrap"]//li[@data-position="1"]//a[@rel]'
brands_buy_button_xpath = '//*[@class="simple-slider-list-wrap"]//li[@data-position="1"]//div[@class="button buy"]'
email_subscribe_input_xpath = '//*[@class="footer"]//*[@class="input" and @type="email"]'
email_subscribe_button_xpath = '//*[@class="footer"]//*[@class="input" and @type="email"]/../following-sibling::button'
facebook_button_xpath = '//*[@class="footer"]//ul[contains(@class, "social")]/child::li[contains(@class, "fb")]'
feedback_link_xpath = '//*[@class="footer"]//descendant::div[@class="footer-columns"]//descendant::p/a[@href]'
callback_button = '//*[@class="header"]//descendant::a[contains(@title, "MAKEUP")]/../child::div/child::div[@data-popup-handler]'
current_language_xpath = '//*[@class="footer-lang"]/child::li[contains(@class, "active")]'
cooperation_link_xpath = '//*[@class="footer-lang"]/parent::div/child::div[@class="cooperation"]/a'
russian_language_xpath = '//*[@class="footer-lang"]/child::li/a[@lang="ru"]'
ukrainian_language_xpath = '//*[@class="footer-lang"]/child::li/a[@lang="uk"]'
about_us_link_xpath = '//div[@class="footer-columns"]//a[@href="/about/"]'
anchor_button_page_up_xpath = '//div[@class="button-up"]'
menu_perfumery_xpath = '//ul[@class="menu-list"]//a[text()="Парфюмерия"or text()="Парфумерія"]'
slider_button_prev_xpath = '//*[@id="slider"]/button[@class="slider-arrow-prev"]'
slider_button_next_xpath = '//*[@id="slider"]/button[@class="slider-arrow-next"]'
main_slider_xpath = '//*[@id="slider"]'
makeup_global_link_pl_xpath = '//a[contains(@href, ".pl")]'
copyright_text_xpath = '//*[contains(text(), "2009-2")]'
block_about_header_xpath = '//*[@class="header-h2"]'
beauty_club_section_xpath = '//li[contains(@class, "beauty-club")]/..'
search_input_xpath = '//*[@id="search-input"]'
promotion_link_xpath = '//header//a[text()="Акції"]'
stories_list_xpath = '//*[@class="swiper-wrapper"]/../parent::div'
main_banner_xpath = '//picture/ancestor::*[@class="slides"]'
payment_link_xpath = '//*[contains(@href, "payment")]'


# 10 css locators for last 10 xpath locators from xpath list above
payment_link_css = '.cols:first-child div a[href*="payment"]'
main_banner_css = '.slides picture'
stories_list_css = '.stories-list'
promotion_link_css = 'header a[href*="actions"]'
search_input_css = '#search-input'
beauty_club_section_css = 'div[class*="beauty-club-slider-posts"]'
block_about_header_css = '.header-h2'
copyright_text_css = 'footer > div div.footer-copy-right'
makeup_global_link_pl_css = 'a[href*=".pl"]'
main_slider_css = '.main-wrap .banner'
